/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AuraIcon {
    }
}
declare global {
    interface HTMLAuraIconElement extends Components.AuraIcon, HTMLStencilElement {
    }
    var HTMLAuraIconElement: {
        prototype: HTMLAuraIconElement;
        new (): HTMLAuraIconElement;
    };
    interface HTMLElementTagNameMap {
        "aura-icon": HTMLAuraIconElement;
    }
}
declare namespace LocalJSX {
    interface AuraIcon {
    }
    interface IntrinsicElements {
        "aura-icon": AuraIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aura-icon": LocalJSX.AuraIcon & JSXBase.HTMLAttributes<HTMLAuraIconElement>;
        }
    }
}
